language: node_js
node_js:
  - 5.0
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  directories:
    - node_modules
before_install:
  - rm .gitignore
  - npm run build
